<template><q-layout view="lHh Lpr lFf" class="certificate-verify"><q-page-container><q-page class="certificate-verify__page"><div class="certificate-verify__card"><q-icon :name="loading ? 'mdi-loading' : valid ? 'mdi-check-decagram-outline' : 'mdi-alert-circle-outline'" size="56px" /><p class="certificate-verify__eyebrow">AITOLEARN / VERIFICACAO</p><h1>{{ loading ? 'Validando certificado' : valid ? 'Certificado valido' : 'Certificado nao encontrado' }}</h1><template v-if="certificate"><p><strong>{{ certificate.user?.name }}</strong> concluiu o curso <strong>{{ certificate.course?.title }}</strong>.</p><div class="certificate-verify__facts"><span>Codigo {{ certificate.certificateNumber }}</span><span>{{ certificate.hours }} horas</span><span>{{ formatDate(certificate.issuedAt) }}</span></div></template><p v-else>Confira o link ou QR code e tente novamente.</p><q-btn flat no-caps color="teal-3" icon="mdi-arrow-left" label="Conhecer AitoLearn" to="/cursos" /></div></q-page></q-page-container></q-layout></template>
<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from 'boot/axios'
const route = useRoute(); const loading = ref(true); const valid = ref(false); const certificate = ref(null)
function formatDate(value) { return value ? new Date(value).toLocaleDateString('pt-BR') : '-' }
onMounted(async () => { try { const response = await api.get(`/certificates/verify/${route.params.token}`); valid.value = Boolean(response.data.data?.valid); certificate.value = response.data.data?.certificate } catch (error) { valid.value = false } finally { loading.value = false } })
</script>
<style scoped>.certificate-verify{color:#effffb;background:#03090b}.certificate-verify__page{display:grid;place-items:center;min-height:100vh;padding:1rem;background:radial-gradient(circle at 50% 20%,rgba(19,188,157,.18),transparent 30rem),#03090b}.certificate-verify__card{display:grid;justify-items:center;gap:.8rem;width:min(94vw,620px);padding:3rem 2rem;border:1px solid rgba(19,188,157,.32);border-radius:1rem;background:rgba(4,24,25,.78);text-align:center}.certificate-verify__card>.q-icon{color:#8fffee}.certificate-verify__eyebrow{margin:0;color:#8fffee;font-size:.65rem;font-weight:900;letter-spacing:.15em}.certificate-verify__card h1{margin:0;font-size:clamp(2rem,5vw,4rem);line-height:1;background:linear-gradient(135deg,#effffb,#13bc9d);background-clip:text;-webkit-background-clip:text;color:transparent}.certificate-verify__card>p:not(.certificate-verify__eyebrow){max-width:36rem;color:rgba(229,255,250,.7);line-height:1.6}.certificate-verify__facts{display:flex;flex-wrap:wrap;justify-content:center;gap:.5rem}.certificate-verify__facts span{padding:.4rem .6rem;border:1px solid rgba(19,188,157,.2);border-radius:999px;color:#8fffee;font-size:.68rem}</style>
