<template><section class="manager"><div class="manager__head"><div><span>AFILIADOS</span><h2>Parceiros da Aito</h2></div><q-btn unelevated no-caps icon="mdi-account-plus-outline" label="Novo afiliado" @click="open()" /></div><q-input v-model="search" outlined dense clearable label="Buscar afiliado" @keyup.enter="load" /><q-table flat bordered class="manager__table" row-key="_id" :rows="rows" :columns="columns" :loading="loading"><template #body-cell-actions="p"><q-td :props="p"><q-btn flat round dense icon="mdi-pencil" @click="open(p.row)" /><q-btn flat round dense color="negative" icon="mdi-delete-outline" @click="remove(p.row)" /></q-td></template></q-table><q-dialog v-model="dialog"><q-card class="manager__dialog"><q-card-section class="row items-center justify-between"><strong>{{ form._id ? 'Editar afiliado' : 'Cadastrar afiliado' }}</strong><q-btn flat round icon="mdi-close" v-close-popup /></q-card-section><q-card-section><q-form @submit.prevent="save"><q-input v-model="form.name" outlined label="Nome" :rules="[required]" /><q-input v-model="form.email" outlined label="E-mail" class="q-mt-sm" :rules="[required]" /><q-input v-model="form.phone" outlined label="Telefone" class="q-mt-sm" /><q-input v-model="form.password" v-if="!form._id" outlined label="Senha inicial" type="password" class="q-mt-sm" :rules="[required]" /><q-input v-model="form.instagram" outlined label="Instagram" class="q-mt-sm" /><q-input v-model="form.tiktok" outlined label="TikTok" class="q-mt-sm" /><q-input v-model="form.youtube" outlined label="YouTube" class="q-mt-sm" /><q-btn unelevated no-caps class="manager__cta full-width q-mt-md" type="submit" label="Salvar" :loading="loading" /></q-form></q-card-section></q-card></q-dialog></section></template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useQuasar } from 'quasar'; import { api } from 'boot/axios'
const $q = useQuasar(); const token = localStorage.getItem('aito_admin_token'); const headers = { headers: { Authorization: `Bearer ${token}` } }; const rows = ref([]); const search = ref(''); const loading = ref(false); const dialog = ref(false); const form = reactive({ name: '', email: '', phone: '', password: '', instagram: '', tiktok: '', youtube: '' }); const columns = [{ name: 'name', label: 'Nome', field: 'name', align: 'left' }, { name: 'email', label: 'E-mail', field: 'email', align: 'left' }, { name: 'active', label: 'Ativo', field: 'active', align: 'center' }, { name: 'actions', label: '', align: 'right' }]
const required = (v) => Boolean(String(v || '').trim()) || 'Obrigatório.'; function reset() { Object.assign(form, { name: '', email: '', phone: '', password: '', instagram: '', tiktok: '', youtube: '' }) }; function open(item) { reset(); if (item) Object.assign(form, { ...item, password: '' }); dialog.value = true }
async function load() { loading.value = true; try { rows.value = (await api.get('/admin/affiliates', { ...headers, params: { q: search.value } })).data.data || [] } catch (e) { $q.notify({ type: 'negative', message: e.response?.data?.message || 'Falha ao carregar afiliados.' }) } finally { loading.value = false } }
async function save() { loading.value = true; try { const response = form._id ? await api.put(`/admin/affiliates/${form._id}`, form, headers) : await api.post('/admin/affiliates', form, headers); dialog.value = false; await load(); $q.notify({ type: 'positive', message: 'Afiliado salvo.' }); return response } catch (e) { $q.notify({ type: 'negative', message: e.response?.data?.message || 'Falha ao salvar afiliado.' }) } finally { loading.value = false } }
function remove(item) { $q.dialog({ title: 'Excluir afiliado', message: `Remover ${item.name}?`, cancel: true }).onOk(async () => { await api.delete(`/admin/affiliates/${item._id}`, headers); await load() }) }; onMounted(load)
</script>
<style scoped>.manager{color:#effffb}.manager__head{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem}.manager__head span{color:#8fffee;font-size:.68rem;font-weight:800;letter-spacing:.14em}.manager h2{margin:.3rem 0 1rem}.manager__head .q-btn,.manager__cta{color:#03110f;background:linear-gradient(135deg,#8fffee,#13bc9d);font-weight:800}.manager__table{margin-top:1rem;background:rgba(4,24,25,.72);color:#effffb}.manager__dialog{width:min(92vw,32rem);color:#effffb;background:#041819}.manager__dialog :deep(.q-field__control){color:#effffb;background:rgba(4,24,25,.8)}.manager__dialog :deep(.q-field__native),.manager__dialog :deep(.q-field__label){color:#effffb}</style>
