<template><section class="admin-certificates"><div><p class="admin-certificates__eyebrow">AITOLEARN / GOVERNANCA</p><h2>Certificados gerados</h2></div><div class="admin-certificates__filters"><q-select v-model="userId" outlined dense clearable label="Filtrar por usuario" :options="userOptions" emit-value map-options @update:model-value="load" /><q-select v-model="courseId" outlined dense clearable label="Filtrar por curso" :options="courseOptions" emit-value map-options @update:model-value="load" /></div><q-table flat bordered wrap-cells row-key="_id" class="admin-certificates__table" :rows="certificates" :columns="columns" :loading="loading" no-data-label="Nenhum certificado gerado"><template #body-cell-user="props"><q-td :props="props">{{ props.row.user?.name }}<small>{{ props.row.user?.email }}</small></q-td></template><template #body-cell-course="props"><q-td :props="props">{{ props.row.course?.title }}</q-td></template><template #body-cell-issuedAt="props"><q-td :props="props">{{ formatDate(props.row.issuedAt) }}</q-td></template><template #body-cell-verify="props"><q-td :props="props"><a :href="`${frontendUrl}/certificados/verificar/${props.row.verificationToken}`" target="_blank" rel="noopener noreferrer">Verificar</a></q-td></template></q-table></section></template>
<script setup>
import { onMounted, ref } from 'vue'
import { api } from 'boot/axios'
const frontendUrl = String(import.meta.env.VITE_FRONTEND_URL || window.location.origin).replace(/\/$/, ''); const token = localStorage.getItem('aito_admin_token'); const headers = { headers: { Authorization: `Bearer ${token}` } }; const loading = ref(false); const certificates = ref([]); const users = ref([]); const courses = ref([]); const userId = ref(''); const courseId = ref(''); const userOptions = ref([]); const courseOptions = ref([]); const columns = [{ name: 'user', label: 'Usuario', field: 'user', align: 'left' }, { name: 'course', label: 'Curso', field: 'course', align: 'left' }, { name: 'hours', label: 'Horas', field: 'hours', align: 'right' }, { name: 'certificateNumber', label: 'Codigo', field: 'certificateNumber', align: 'left' }, { name: 'issuedAt', label: 'Emissao', field: 'issuedAt', align: 'left' }, { name: 'verify', label: '', align: 'right' }]
function formatDate(value) { return value ? new Date(value).toLocaleDateString('pt-BR') : '-' }
async function load() { loading.value = true; try { const [certificateResponse, userResponse, courseResponse] = await Promise.all([api.get('/admin/certificates', { ...headers, params: { userId: userId.value || undefined, courseId: courseId.value || undefined } }), api.get('/admin/users', headers), api.get('/admin/courses', headers)]); certificates.value = certificateResponse.data.data || []; users.value = userResponse.data.data || []; courses.value = courseResponse.data.data || []; userOptions.value = users.value.map((item) => ({ label: `${item.name} - ${item.email}`, value: item._id })); courseOptions.value = courses.value.map((item) => ({ label: item.title, value: item._id })) } finally { loading.value = false } }
onMounted(load)
</script>
<style scoped>.admin-certificates{display:grid;gap:1rem;color:#effffb}.admin-certificates__eyebrow{margin:0;color:#8fffee;font-size:.65rem;font-weight:900;letter-spacing:.15em;text-transform:uppercase}.admin-certificates h2{margin:.5rem 0 0;font-size:clamp(1.6rem,3vw,2.8rem)}.admin-certificates__filters{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.admin-certificates__filters :deep(.q-field__control){color:#effffb;background:rgba(7,40,40,.74)}.admin-certificates__filters :deep(.q-field__native),.admin-certificates__filters :deep(.q-field__label){color:rgba(239,255,251,.8)}.admin-certificates__table{color:#effffb;background:rgba(3,16,18,.58);border-color:rgba(19,188,157,.2)}.admin-certificates__table :deep(th){color:#8fffee;font-size:.68rem}.admin-certificates__table :deep(td){color:rgba(239,255,251,.78);font-size:.72rem}.admin-certificates__table small{display:block;color:rgba(239,255,251,.5);font-size:.62rem}.admin-certificates__table a{color:#8fffee;text-decoration:none}@media(max-width:700px){.admin-certificates__filters{grid-template-columns:1fr}}
</style>
