<template><section class="course-purchases"><div class="course-purchases__head"><div><p class="course-purchases__eyebrow">AITOLEARN / FINANCEIRO</p><h2>Compras de cursos</h2></div><q-btn flat round icon="mdi-refresh" aria-label="Atualizar compras" :loading="loading" @click="load" /></div><div class="course-purchases__filters"><q-select v-model="userId" outlined dense clearable label="Filtrar por usuario" :options="userOptions" emit-value map-options @update:model-value="load" /><q-select v-model="status" outlined dense clearable label="Status" :options="statusOptions" emit-value map-options @update:model-value="load" /></div><div class="course-purchases__metrics"><article><span>Interacoes registradas</span><strong>{{ metrics.total || 0 }}</strong></article><article><span>Curso mais buscado</span><strong>{{ metrics.topCourses?.[0]?.course?.title || '-' }}</strong></article><article><span>Usuarios monitorados</span><strong>{{ metrics.topUsers?.length || 0 }}</strong></article></div><q-table flat bordered wrap-cells row-key="_id" class="course-purchases__table" :rows="purchases" :columns="columns" :loading="loading" no-data-label="Nenhuma compra encontrada"><template #body-cell-user="props"><q-td :props="props">{{ props.row.user?.name }}<small>{{ props.row.user?.email }}</small></q-td></template><template #body-cell-course="props"><q-td :props="props">{{ props.row.course?.title }}</q-td></template><template #body-cell-amount="props"><q-td :props="props">{{ money(props.row.amount) }}</q-td></template><template #body-cell-status="props"><q-td :props="props"><span class="course-purchases__tag">{{ props.row.status }}</span></q-td></template><template #body-cell-createdAt="props"><q-td :props="props">{{ formatDate(props.row.createdAt) }}</q-td></template></q-table><div class="course-purchases__ranking"><div><p class="course-purchases__eyebrow">Cursos mais pesquisados e vistos</p><div v-for="item in metrics.topCourses || []" :key="item._id"><span>{{ item.course?.title || 'Curso removido' }}</span><strong>{{ item.total }}</strong></div></div><div><p class="course-purchases__eyebrow">Usuarios com interacoes</p><div v-for="item in metrics.topUsers || []" :key="item._id"><span>{{ item.user?.name || item.user?.email || 'Usuario' }}</span><strong>{{ item.total }}</strong></div></div></div></section></template>
<script setup>
import { onMounted, ref } from 'vue'
import { api } from 'boot/axios'
const token = localStorage.getItem('aito_admin_token'); const headers = { headers: { Authorization: `Bearer ${token}` } }; const loading = ref(false); const purchases = ref([]); const users = ref([]); const userId = ref(''); const status = ref(''); const metrics = ref({}); const statusOptions = [{ label: 'Pendente', value: 'pending' }, { label: 'Pago', value: 'paid' }, { label: 'Cancelado', value: 'cancelled' }]; const columns = [{ name: 'user', label: 'Usuario', field: 'user', align: 'left' }, { name: 'course', label: 'Curso', field: 'course', align: 'left' }, { name: 'amount', label: 'Valor', field: 'amount', align: 'right' }, { name: 'status', label: 'Status', field: 'status', align: 'center' }, { name: 'createdAt', label: 'Data', field: 'createdAt', align: 'left' }]
const userOptions = ref([])
function money(value) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0)) }
function formatDate(value) { return value ? new Date(value).toLocaleDateString('pt-BR') : '-' }
async function load() { loading.value = true; try { const [purchaseResponse, metricResponse, userResponse] = await Promise.all([api.get('/admin/course-purchases', { ...headers, params: { userId: userId.value || undefined, status: status.value || undefined } }), api.get('/admin/courses/metrics', { ...headers, params: { userId: userId.value || undefined } }), api.get('/admin/users', headers)]); purchases.value = purchaseResponse.data.data || []; metrics.value = metricResponse.data.data || {}; users.value = userResponse.data.data || []; userOptions.value = users.value.map((item) => ({ label: `${item.name} - ${item.email}`, value: item._id })) } finally { loading.value = false } }
onMounted(load)
</script>
<style scoped>.course-purchases{display:grid;gap:1rem;color:#effffb}.course-purchases__head{display:flex;justify-content:space-between;align-items:flex-end}.course-purchases__eyebrow{margin:0;color:#8fffee;font-size:.65rem;font-weight:900;letter-spacing:.15em;text-transform:uppercase}.course-purchases h2{margin:.5rem 0 0;font-size:clamp(1.6rem,3vw,2.8rem)}.course-purchases__filters{display:grid;grid-template-columns:1fr 220px;gap:.6rem}.course-purchases__filters :deep(.q-field__control){color:#effffb;background:rgba(7,40,40,.74)}.course-purchases__filters :deep(.q-field__native),.course-purchases__filters :deep(.q-field__label){color:rgba(239,255,251,.8)}.course-purchases__metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem}.course-purchases__metrics article{display:grid;gap:.3rem;padding:1rem;border:1px solid rgba(19,188,157,.22);border-radius:.6rem;background:rgba(4,24,25,.66)}.course-purchases__metrics span{color:rgba(229,255,250,.56);font-size:.67rem}.course-purchases__metrics strong{color:#8fffee;font-size:1.15rem}.course-purchases__table{color:#effffb;background:rgba(3,16,18,.58);border-color:rgba(19,188,157,.2)}.course-purchases__table :deep(th){color:#8fffee;font-size:.68rem}.course-purchases__table :deep(td){color:rgba(239,255,251,.78);font-size:.72rem}.course-purchases__table small{display:block;color:rgba(239,255,251,.5);font-size:.62rem}.course-purchases__tag{color:#8fffee}.course-purchases__ranking{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.course-purchases__ranking>div{display:grid;gap:.5rem;padding:1rem;border:1px solid rgba(19,188,157,.2);border-radius:.6rem;background:rgba(4,24,25,.62)}.course-purchases__ranking>div>div{display:flex;justify-content:space-between;color:rgba(239,255,251,.72);font-size:.75rem}.course-purchases__ranking strong{color:#8fffee}@media(max-width:700px){.course-purchases__filters,.course-purchases__metrics,.course-purchases__ranking{grid-template-columns:1fr}}
</style>
