<template><section class="user-certificates"><div class="user-certificates__head"><div><p class="user-certificates__eyebrow">AITOLEARN / CERTIFICADOS</p><h1>Suas conquistas.</h1></div></div><div v-if="loading" class="user-certificates__loading"><q-spinner color="teal-3" size="32px" /></div><div v-else class="user-certificates__grid"><article v-for="certificate in certificates" :key="certificate._id" class="certificate-card"><div><p class="user-certificates__eyebrow">AitoSoftwares certifica</p><h2>{{ certificate.user?.name || userName }}</h2><span>concluiu</span><h3>{{ certificate.course?.title }}</h3><span>{{ certificate.hours }} horas · {{ formatDate(certificate.issuedAt) }}</span></div><img :src="certificate.qrCodeDataUrl" alt="QR code de verificacao" /><small>{{ certificate.certificateNumber }}</small><q-btn flat no-caps color="teal-3" icon="mdi-qrcode-scan" label="Verificar certificado" @click="router.push(`/certificados/verificar/${certificate.verificationToken}`)" /></article><div v-if="!certificates.length" class="user-certificates__empty"><q-icon name="mdi-certificate-outline" size="54px" /><strong>Conclua uma trilha para gerar seu certificado.</strong></div></div></section></template>
<script setup>
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from 'boot/axios'
const router = useRouter(); const certificates = ref([]); const loading = ref(true); const userName = JSON.parse(localStorage.getItem('aito_user') || '{}').name || 'Usuario'; const headers = { headers: { Authorization: `Bearer ${localStorage.getItem('aito_user_token')}` } }
function formatDate(value) { return value ? new Date(value).toLocaleDateString('pt-BR') : '-' }
onMounted(async () => { try { const response = await api.get('/certificates', headers); certificates.value = response.data.data || [] } finally { loading.value = false } })
</script>
<style scoped>.user-certificates{display:grid;gap:1.4rem}.user-certificates__head h1{margin:.6rem 0 0;font-size:clamp(2rem,5vw,4rem);line-height:.98;background:linear-gradient(135deg,#effffb,#13bc9d);background-clip:text;-webkit-background-clip:text;color:transparent}.user-certificates__eyebrow{margin:0;color:#8fffee;font-size:.65rem;font-weight:900;letter-spacing:.15em;text-transform:uppercase}.user-certificates__grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:.8rem}.certificate-card{position:relative;display:grid;gap:.7rem;min-height:290px;padding:1.2rem;border:1px solid rgba(19,188,157,.3);border-radius:.75rem;background:linear-gradient(135deg,rgba(9,48,47,.82),rgba(3,16,18,.8));overflow:hidden}.certificate-card h2{margin:.8rem 0 .2rem;font-size:1rem;color:#effffb}.certificate-card h3{margin:.35rem 0;color:#8fffee;font-size:1.3rem}.certificate-card span{color:rgba(239,255,251,.65);font-size:.72rem}.certificate-card img{position:absolute;right:1rem;bottom:3.2rem;width:82px;height:82px;background:#f1fffc}.certificate-card small{color:rgba(239,255,251,.52);font-size:.62rem}.certificate-card .q-btn{justify-self:start}.user-certificates__loading,.user-certificates__empty{display:grid;justify-items:center;gap:.7rem;padding:4rem;color:rgba(229,255,250,.62);text-align:center}.user-certificates__empty .q-icon{color:#8fffee}@media(max-width:600px){.certificate-card img{width:68px;height:68px}}
</style>
