<template><section class="user-courses"><div class="user-courses__head"><div><p class="user-courses__eyebrow">AITOLEARN / MEUS CURSOS</p><h1>Continue de onde parou.</h1></div><q-btn outline no-caps color="teal-3" icon="mdi-storefront-outline" label="Explorar cursos" @click="router.push('/cursos')" /></div><div v-if="loading" class="user-courses__loading"><q-spinner color="teal-3" size="32px" /></div><div v-else-if="courses.length" class="user-courses__grid"><article v-for="item in courses" :key="item._id" class="user-course-card"><img v-if="item.course?.banner" :src="item.course.banner.url" :alt="item.course.title" /><div v-else class="user-course-card__placeholder"><q-icon name="mdi-school-outline" size="38px" /></div><div class="user-course-card__body"><p class="user-courses__eyebrow">{{ item.status === 'completed' ? 'Concluido' : 'Em andamento' }}</p><h2>{{ item.course?.title }}</h2><div class="user-course-card__progress"><div><span>Progresso</span><strong>{{ item.progress || 0 }}%</strong></div><div><i :style="{ width: `${item.progress || 0}%` }"></i></div></div><q-btn unelevated no-caps class="user-courses__button full-width" icon="mdi-play" label="Abrir curso" @click="router.push(`/cursos/${item.course?.slug}/aulas`)" /></div></article></div><div v-else class="user-courses__empty"><q-icon name="mdi-school-outline" size="54px" /><strong>Seus cursos comprados aparecem aqui.</strong><span>Explore o catalogo e escolha sua proxima trilha.</span><q-btn unelevated no-caps class="user-courses__button" label="Ver catalogo" icon="mdi-arrow-right" @click="router.push('/cursos')" /></div></section></template>
<script setup>
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from 'boot/axios'
const router = useRouter(); const courses = ref([]); const loading = ref(true); const token = localStorage.getItem('aito_user_token'); const headers = { headers: { Authorization: `Bearer ${token}` } }
onMounted(async () => { try { const response = await api.get('/courses/me', headers); courses.value = response.data.data || [] } finally { loading.value = false } })
</script>
<style scoped>.user-courses{display:grid;gap:1.4rem}.user-courses__head{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem}.user-courses__eyebrow{margin:0;color:#8fffee;font-size:.65rem;font-weight:900;letter-spacing:.15em;text-transform:uppercase}.user-courses h1{margin:.6rem 0 0;font-size:clamp(2rem,5vw,4.5rem);line-height:.98;background:linear-gradient(135deg,#effffb,#13bc9d);background-clip:text;-webkit-background-clip:text;color:transparent}.user-courses__grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.8rem}.user-course-card{overflow:hidden;border:1px solid rgba(19,188,157,.23);border-radius:.7rem;background:rgba(4,24,25,.74)}.user-course-card>img,.user-course-card__placeholder{width:100%;aspect-ratio:16/8;object-fit:cover}.user-course-card__placeholder{display:grid;place-items:center;color:#8fffee;background:rgba(19,188,157,.12)}.user-course-card__body{display:grid;gap:.6rem;padding:1rem}.user-course-card h2{margin:0;font-size:1rem}.user-course-card__progress{display:grid;gap:.4rem}.user-course-card__progress>div:first-child{display:flex;justify-content:space-between;color:rgba(229,255,250,.6);font-size:.67rem}.user-course-card__progress strong{color:#8fffee}.user-course-card__progress>div:last-child{height:5px;overflow:hidden;border-radius:5px;background:rgba(143,255,238,.1)}.user-course-card__progress i{display:block;height:100%;background:#13bc9d}.user-courses__button{color:#03110f;background:linear-gradient(135deg,#8fffee,#13bc9d);font-weight:900}.user-courses__loading,.user-courses__empty{display:grid;justify-items:center;gap:.7rem;padding:4rem 1rem;color:rgba(229,255,250,.62);text-align:center}.user-courses__empty .q-icon{color:#8fffee}.user-courses__empty strong{color:#effffb}@media(max-width:800px){.user-courses__head{align-items:flex-start;flex-direction:column}.user-courses__head .q-btn{width:100%}.user-courses__grid{grid-template-columns:1fr}}
</style>
